services:
  - type: web
    name: springcurse
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/proyecto-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
